---
resources:
  - name: resource-uname
    type: git
    source:
      url: https://github.com/derekhawkesworth-vioohnet/concourse
      branch: master

jobs:
  - name: job-uname
    public: true
    plan:
      - get: resource-uname
      - task: uname
        file: pipeline2.yml
