---
resources:
  - name: resource-uname
    type: git
    source:
      uri: https://github.com/derekhawkesworth-vioohnet/concourse.git
      branch: master

  - name: my-timer
      type: time
      source:
        interval: 2m

jobs:
  - name: job-uname
    public: true
    plan:
      - get: resource-uname
      - task: uname
        file: resource-uname/task.yml
