---
resources:
  - name: resource-uname
    type: git
    source:
      uri: https://github.com/derekhawkesworth-vioohnet/concourse.git
      branch: master

jobs:
  - name: job-uname
    public: true
    plan:
      - get: resource-uname
        trigger: true
      - task: uname
        file: resource-uname/task.yml
