---
jobs:
  - name: job-uname
    public: true
    plan:
      - task: uname
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: uname
            args: [-a]
